services:
  nextjs:
    image: zk-website
    volumes:
      - /app/.next/static:/usr/share/nginx/html/_next/static
      # - /app/.next/static:/app/.next/static
    networks:
      - nextjs-net
    ports:
      - "3000:3000" # 端口映射（对应 -p 参数，网页3、网页9）
    restart: unless-stopped # 后台运行策略（默认行为，参考网页5）

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /app/.next/static:/usr/share/nginx/html/_next/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    networks:
      - nextjs-net
    depends_on:
      - nextjs # 服务名，在nginx.conf中能用到          


networks:
  nextjs-net:
    name: nextjs-net
    driver: bridge